#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export FZ_CAMERA_INDEX="${FZ_CAMERA_INDEX:-0}"
export FZ_CAMERA_WIDTH="${FZ_CAMERA_WIDTH:-640}"
export FZ_CAMERA_HEIGHT="${FZ_CAMERA_HEIGHT:-480}"
export FZ_CAMERA_FPS="${FZ_CAMERA_FPS:-20}"
export FZ_REMOTE_BIND="${FZ_REMOTE_BIND:-0.0.0.0}"
export FZ_REMOTE_PORT="${FZ_REMOTE_PORT:-8765}"
export FZ_REMOTE_STREAM_FPS="${FZ_REMOTE_STREAM_FPS:-5}"
export FZ_REMOTE_JPEG_QUALITY="${FZ_REMOTE_JPEG_QUALITY:-65}"
export FZ_PROFILE="${FZ_PROFILE:-pi3_field}"
export FZ_ROBOT_SERIAL_PORT="${FZ_ROBOT_SERIAL_PORT:-/dev/ttyACM0}"
export FZ_ROBOT_BAUD="${FZ_ROBOT_BAUD:-115200}"
export FZ_ROBOT_GREEN_FORWARD_MS="${FZ_ROBOT_GREEN_FORWARD_MS:-5000}"
export FZ_ROBOT_GREEN_STREAK="${FZ_ROBOT_GREEN_STREAK:-2}"
export FZ_ROBOT_GREEN_COOLDOWN_MS="${FZ_ROBOT_GREEN_COOLDOWN_MS:-6000}"
export FZ_ROBOT_GREEN_HOLD_MS="${FZ_ROBOT_GREEN_HOLD_MS:-900}"
export FZ_ROBOT_OBSTACLE_HOLD_MS="${FZ_ROBOT_OBSTACLE_HOLD_MS:-1200}"
export FZ_ROBOT_DRY_RUN="${FZ_ROBOT_DRY_RUN:-0}"

exec "${SCRIPT_DIR}/run_pi_headless.sh" "$@"
