#!/usr/bin/env bash

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck source=runtime_common.sh
. "${SCRIPT_DIR}/runtime_common.sh"

ENV_FILE="${FZ_DEFAULT_ENV_FILE}"
EXTRA_ARGS=()
while [[ $# -gt 0 ]]; do
    case "$1" in
        --env-file)
            ENV_FILE="$2"
            shift 2
            ;;
        *)
            EXTRA_ARGS+=("$1")
            shift
            ;;
    esac
done

fz_load_env "${ENV_FILE}"
PYTHON_BIN="$(fz_python_bin)"
fz_require_file "${FZ_PROJECT_ROOT}/src/live_dashboard_runner.py"

CAMERA_INDEX="${FZ_CAMERA_INDEX:-0}"
CAMERA_WIDTH="${FZ_CAMERA_WIDTH:-640}"
CAMERA_HEIGHT="${FZ_CAMERA_HEIGHT:-480}"
CAMERA_FPS="${FZ_CAMERA_FPS:-20}"
CAMERA_BACKEND="${FZ_CAMERA_BACKEND:-auto}"
CAMERA_ROTATION="${FZ_CAMERA_ROTATION:-0}"
REMOTE_BIND="${FZ_REMOTE_BIND:-0.0.0.0}"
REMOTE_PORT="${FZ_REMOTE_PORT:-8765}"
REMOTE_STREAM_FPS="${FZ_REMOTE_STREAM_FPS:-5}"
REMOTE_JPEG_QUALITY="${FZ_REMOTE_JPEG_QUALITY:-65}"
VISION_CONFIG="${FZ_VISION_CONFIG:-New_AI/obr_overengineering_v1/configs/vision_config.json}"
ROBOT_BAUD="${FZ_ROBOT_BAUD:-115200}"
ROBOT_BACKEND="${FZ_ROBOT_BACKEND:-serial}"
ROBOT_GREEN_FORWARD_MS="${FZ_ROBOT_GREEN_FORWARD_MS:-5000}"
ROBOT_GREEN_STREAK="${FZ_ROBOT_GREEN_STREAK:-2}"
ROBOT_GREEN_CONFIRM_HOLD_MS="${FZ_ROBOT_GREEN_CONFIRM_HOLD_MS:-180}"
ROBOT_GREEN_COOLDOWN_MS="${FZ_ROBOT_GREEN_COOLDOWN_MS:-6000}"
ROBOT_GREEN_HOLD_MS="${FZ_ROBOT_GREEN_HOLD_MS:-900}"
ROBOT_OBSTACLE_HOLD_MS="${FZ_ROBOT_OBSTACLE_HOLD_MS:-1200}"
PCA9685_I2C_ADDRESS="${FZ_PCA9685_I2C_ADDRESS:-0x40}"
PCA9685_FREQUENCY_HZ="${FZ_PCA9685_FREQUENCY_HZ:-50}"
PCA9685_LEFT_CHANNEL="${FZ_PCA9685_LEFT_CHANNEL:-4}"
PCA9685_RIGHT_CHANNEL="${FZ_PCA9685_RIGHT_CHANNEL:-0}"
PCA9685_LEFT_CHANNELS="${FZ_PCA9685_LEFT_CHANNELS:-4,5}"
PCA9685_RIGHT_CHANNELS="${FZ_PCA9685_RIGHT_CHANNELS:-0,1}"
PCA9685_MIN_US="${FZ_PCA9685_MIN_US:-1000}"
PCA9685_NEUTRAL_US="${FZ_PCA9685_NEUTRAL_US:-1600}"
PCA9685_MAX_US="${FZ_PCA9685_MAX_US:-2000}"
PCA9685_BASE_THROTTLE_US="${FZ_PCA9685_BASE_THROTTLE_US:-}"
PCA9685_LEFT_BASE_THROTTLE_US="${FZ_PCA9685_LEFT_BASE_THROTTLE_US:-300}"
PCA9685_RIGHT_BASE_THROTTLE_US="${FZ_PCA9685_RIGHT_BASE_THROTTLE_US:-200}"
PCA9685_TURN_GAIN_US="${FZ_PCA9685_TURN_GAIN_US:-220}"
PCA9685_PID_KP_US="${FZ_PCA9685_PID_KP_US:-320}"
PCA9685_PID_KI_US="${FZ_PCA9685_PID_KI_US:-0}"
PCA9685_PID_KD_US="${FZ_PCA9685_PID_KD_US:-12}"
PCA9685_PID_INTEGRAL_LIMIT="${FZ_PCA9685_PID_INTEGRAL_LIMIT:-0.15}"
PCA9685_PID_DERIVATIVE_FILTER="${FZ_PCA9685_PID_DERIVATIVE_FILTER:-0.60}"
PCA9685_LINE_HOLD_MS="${FZ_PCA9685_LINE_HOLD_MS:-120}"
PCA9685_GAP_CROSSING_ENABLED="${FZ_PCA9685_GAP_CROSSING_ENABLED:-0}"
PCA9685_GAP_STRAIGHT_CONFIRM_FRAMES="${FZ_PCA9685_GAP_STRAIGHT_CONFIRM_FRAMES:-3}"
PCA9685_GAP_REACQUIRE_CONFIRM_FRAMES="${FZ_PCA9685_GAP_REACQUIRE_CONFIRM_FRAMES:-2}"
PCA9685_GAP_CROSSING_TIMEOUT_MS="${FZ_PCA9685_GAP_CROSSING_TIMEOUT_MS:-2200}"
PCA9685_GAP_MAX_ENTRY_ERROR="${FZ_PCA9685_GAP_MAX_ENTRY_ERROR:-0.22}"
PCA9685_GAP_MAX_ENTRY_BEND="${FZ_PCA9685_GAP_MAX_ENTRY_BEND:-0.18}"
PCA9685_MAX_OUTPUT_US="${FZ_PCA9685_MAX_OUTPUT_US:-240}"
PCA9685_LINE_ERROR_DEADBAND="${FZ_PCA9685_LINE_ERROR_DEADBAND:-0.025}"
PCA9685_SIMPLE_LINE_FOLLOW="${FZ_PCA9685_SIMPLE_LINE_FOLLOW:-0}"
PCA9685_BASIC_LINE_FOLLOW="${FZ_PCA9685_BASIC_LINE_FOLLOW:-0}"
PCA9685_LINE_STEERING_INVERTED="${FZ_PCA9685_LINE_STEERING_INVERTED:-0}"
PCA9685_SHARP_CORNER_MANEUVER_ENABLED="${FZ_PCA9685_SHARP_CORNER_MANEUVER_ENABLED:-1}"
PCA9685_CORNER_SEQUENCE_ENABLED="${FZ_PCA9685_CORNER_SEQUENCE_ENABLED:-0}"
PCA9685_CORNER_CONFIRM_FRAMES="${FZ_PCA9685_CORNER_CONFIRM_FRAMES:-2}"
PCA9685_CORNER_MIN_ELBOW_ROW_CONTRAST="${FZ_PCA9685_CORNER_MIN_ELBOW_ROW_CONTRAST:-1.25}"
PCA9685_CORNER_MIN_WIDE_ROW_OCCUPANCY="${FZ_PCA9685_CORNER_MIN_WIDE_ROW_OCCUPANCY:-0.68}"
PCA9685_CORNER_APPROACH_STOP_ROW_RATIO="${FZ_PCA9685_CORNER_APPROACH_STOP_ROW_RATIO:-0.40}"
PCA9685_CORNER_APPROACH_THROTTLE_SCALE="${FZ_PCA9685_CORNER_APPROACH_THROTTLE_SCALE:-0.72}"
PCA9685_CORNER_APPROACH_MIN_MS="${FZ_PCA9685_CORNER_APPROACH_MIN_MS:-350}"
PCA9685_CORNER_APPROACH_LEFT_MIN_MS="${FZ_PCA9685_CORNER_APPROACH_LEFT_MIN_MS:-550}"
PCA9685_CORNER_BRAKE_MS="${FZ_PCA9685_CORNER_BRAKE_MS:-500}"
PCA9685_CORNER_PIVOT_SPEED_US="${FZ_PCA9685_CORNER_PIVOT_SPEED_US:-300}"
PCA9685_CORNER_PIVOT_RIGHT_MS="${FZ_PCA9685_CORNER_PIVOT_RIGHT_MS:-1900}"
PCA9685_CORNER_PIVOT_LEFT_MS="${FZ_PCA9685_CORNER_PIVOT_LEFT_MS:-2100}"
PCA9685_CORNER_REACQUIRE_SPEED_US="${FZ_PCA9685_CORNER_REACQUIRE_SPEED_US:-130}"
PCA9685_CORNER_REACQUIRE_TIMEOUT_MS="${FZ_PCA9685_CORNER_REACQUIRE_TIMEOUT_MS:-1200}"
PCA9685_CURVE_LOOKAHEAD_GAIN="${FZ_PCA9685_CURVE_LOOKAHEAD_GAIN:-0}"
PCA9685_CURVE_THROTTLE_SCALE="${FZ_PCA9685_CURVE_THROTTLE_SCALE:-1.0}"
PCA9685_ORDINARY_SHARP_HOLD_MS="${FZ_PCA9685_ORDINARY_SHARP_HOLD_MS:-900}"
PCA9685_SHARP_CURVE_THRESHOLD="${FZ_PCA9685_SHARP_CURVE_THRESHOLD:-0.55}"
PCA9685_SHARP_CURVE_HOLD_MS="${FZ_PCA9685_SHARP_CURVE_HOLD_MS:-900}"
PCA9685_SHARP_CURVE_OUTER_SCALE="${FZ_PCA9685_SHARP_CURVE_OUTER_SCALE:-1.0}"
PCA9685_SHARP_CURVE_INNER_REVERSE_SCALE="${FZ_PCA9685_SHARP_CURVE_INNER_REVERSE_SCALE:-1.0}"
PCA9685_SHARP_CURVE_ENTRY_MIN_ROW_RATIO="${FZ_PCA9685_SHARP_CURVE_ENTRY_MIN_ROW_RATIO:-0.0}"
PCA9685_SHARP_CURVE_VISIBLE_COMMIT_MS="${FZ_PCA9685_SHARP_CURVE_VISIBLE_COMMIT_MS:-2600}"
PCA9685_SHARP_CURVE_FINISH_INNER_REVERSE_SCALE="${FZ_PCA9685_SHARP_CURVE_FINISH_INNER_REVERSE_SCALE:-1.0}"
PCA9685_SHARP_CURVE_EXIT_SETTLE_MS="${FZ_PCA9685_SHARP_CURVE_EXIT_SETTLE_MS:-320}"
PCA9685_SHARP_CURVE_EXIT_THROTTLE_SCALE="${FZ_PCA9685_SHARP_CURVE_EXIT_THROTTLE_SCALE:-1.0}"
PCA9685_SHARP_CURVE_EXIT_MAX_CORRECTION_US="${FZ_PCA9685_SHARP_CURVE_EXIT_MAX_CORRECTION_US:-0}"
PCA9685_SHARP_CURVE_RECOVERY_MS="${FZ_PCA9685_SHARP_CURVE_RECOVERY_MS:-520}"
PCA9685_SHARP_CURVE_RECOVERY_MAX_CORRECTION_US="${FZ_PCA9685_SHARP_CURVE_RECOVERY_MAX_CORRECTION_US:-45}"
PCA9685_GREEN_TURN_US="${FZ_PCA9685_GREEN_TURN_US:-260}"
PCA9685_GREEN_HALF_TURN_US="${FZ_PCA9685_GREEN_HALF_TURN_US:-300}"
PCA9685_GREEN_HALF_TURN_MS="${FZ_PCA9685_GREEN_HALF_TURN_MS:-4000}"
PCA9685_GREEN_HALF_TURN_FIRST_MS="${FZ_PCA9685_GREEN_HALF_TURN_FIRST_MS:-1900}"
PCA9685_GREEN_HALF_TURN_SECOND_MS="${FZ_PCA9685_GREEN_HALF_TURN_SECOND_MS:-2100}"
PCA9685_GREEN_HALF_TURN_REVERSE_MS="${FZ_PCA9685_GREEN_HALF_TURN_REVERSE_MS:-550}"
PCA9685_GREEN_MANEUVERS_ENABLED="${FZ_PCA9685_GREEN_MANEUVERS_ENABLED:-1}"
PCA9685_START_DISARMED="${FZ_PCA9685_START_DISARMED:-0}"
PROFILE_NAME="${FZ_PROFILE:-}"
RECORDINGS_ROOT="${FZ_RECORDINGS_ROOT:-}"
LED1_GPIO="${FZ_LED1_GPIO:-18}"
LED2_GPIO="${FZ_LED2_GPIO:-23}"
ENABLE_MASTER_SWITCH="${FZ_ENABLE_MASTER_SWITCH:-0}"
MASTER_SWITCH_GPIO="${FZ_MASTER_SWITCH_GPIO:-17}"
MASTER_SWITCH_DEBOUNCE_MS="${FZ_MASTER_SWITCH_DEBOUNCE_MS:-20}"

ARGS=(
    "${FZ_PROJECT_ROOT}/src/live_dashboard_runner.py"
    --headless
    --camera-index "${CAMERA_INDEX}"
    --camera-width "${CAMERA_WIDTH}"
    --camera-height "${CAMERA_HEIGHT}"
    --camera-fps "${CAMERA_FPS}"
    --camera-backend "${CAMERA_BACKEND}"
    --camera-rotation "${CAMERA_ROTATION}"
    --config "${VISION_CONFIG}"
    --remote-bind "${REMOTE_BIND}"
    --remote-port "${REMOTE_PORT}"
    --remote-stream-fps "${REMOTE_STREAM_FPS}"
    --remote-jpeg-quality "${REMOTE_JPEG_QUALITY}"
    --robot-backend "${ROBOT_BACKEND}"
    --robot-baud "${ROBOT_BAUD}"
    --robot-green-forward-ms "${ROBOT_GREEN_FORWARD_MS}"
    --robot-green-streak "${ROBOT_GREEN_STREAK}"
    --robot-green-confirm-hold-ms "${ROBOT_GREEN_CONFIRM_HOLD_MS}"
    --robot-green-cooldown-ms "${ROBOT_GREEN_COOLDOWN_MS}"
    --robot-green-hold-ms "${ROBOT_GREEN_HOLD_MS}"
    --robot-obstacle-hold-ms "${ROBOT_OBSTACLE_HOLD_MS}"
    --pca9685-i2c-address "${PCA9685_I2C_ADDRESS}"
    --pca9685-frequency-hz "${PCA9685_FREQUENCY_HZ}"
    --pca9685-left-channel "${PCA9685_LEFT_CHANNEL}"
    --pca9685-right-channel "${PCA9685_RIGHT_CHANNEL}"
    --pca9685-min-us "${PCA9685_MIN_US}"
    --pca9685-neutral-us "${PCA9685_NEUTRAL_US}"
    --pca9685-max-us "${PCA9685_MAX_US}"
    --pca9685-left-base-throttle-us "${PCA9685_LEFT_BASE_THROTTLE_US}"
    --pca9685-right-base-throttle-us "${PCA9685_RIGHT_BASE_THROTTLE_US}"
    --pca9685-turn-gain-us "${PCA9685_TURN_GAIN_US}"
    --pca9685-pid-kp-us "${PCA9685_PID_KP_US}"
    --pca9685-pid-ki-us "${PCA9685_PID_KI_US}"
    --pca9685-pid-kd-us "${PCA9685_PID_KD_US}"
    --pca9685-pid-integral-limit "${PCA9685_PID_INTEGRAL_LIMIT}"
    --pca9685-pid-derivative-filter "${PCA9685_PID_DERIVATIVE_FILTER}"
    --pca9685-line-hold-ms "${PCA9685_LINE_HOLD_MS}"
    --pca9685-gap-straight-confirm-frames "${PCA9685_GAP_STRAIGHT_CONFIRM_FRAMES}"
    --pca9685-gap-reacquire-confirm-frames "${PCA9685_GAP_REACQUIRE_CONFIRM_FRAMES}"
    --pca9685-gap-crossing-timeout-ms "${PCA9685_GAP_CROSSING_TIMEOUT_MS}"
    --pca9685-gap-max-entry-error "${PCA9685_GAP_MAX_ENTRY_ERROR}"
    --pca9685-gap-max-entry-bend "${PCA9685_GAP_MAX_ENTRY_BEND}"
    --pca9685-max-output-us "${PCA9685_MAX_OUTPUT_US}"
    --pca9685-line-error-deadband "${PCA9685_LINE_ERROR_DEADBAND}"
    --pca9685-corner-confirm-frames "${PCA9685_CORNER_CONFIRM_FRAMES}"
    --pca9685-corner-min-elbow-row-contrast "${PCA9685_CORNER_MIN_ELBOW_ROW_CONTRAST}"
    --pca9685-corner-min-wide-row-occupancy "${PCA9685_CORNER_MIN_WIDE_ROW_OCCUPANCY}"
    --pca9685-corner-approach-stop-row-ratio "${PCA9685_CORNER_APPROACH_STOP_ROW_RATIO}"
    --pca9685-corner-approach-throttle-scale "${PCA9685_CORNER_APPROACH_THROTTLE_SCALE}"
    --pca9685-corner-approach-min-ms "${PCA9685_CORNER_APPROACH_MIN_MS}"
    --pca9685-corner-approach-left-min-ms "${PCA9685_CORNER_APPROACH_LEFT_MIN_MS}"
    --pca9685-corner-brake-ms "${PCA9685_CORNER_BRAKE_MS}"
    --pca9685-corner-pivot-speed-us "${PCA9685_CORNER_PIVOT_SPEED_US}"
    --pca9685-corner-pivot-right-ms "${PCA9685_CORNER_PIVOT_RIGHT_MS}"
    --pca9685-corner-pivot-left-ms "${PCA9685_CORNER_PIVOT_LEFT_MS}"
    --pca9685-corner-reacquire-speed-us "${PCA9685_CORNER_REACQUIRE_SPEED_US}"
    --pca9685-corner-reacquire-timeout-ms "${PCA9685_CORNER_REACQUIRE_TIMEOUT_MS}"
    --pca9685-curve-lookahead-gain "${PCA9685_CURVE_LOOKAHEAD_GAIN}"
    --pca9685-curve-throttle-scale "${PCA9685_CURVE_THROTTLE_SCALE}"
    --pca9685-ordinary-sharp-hold-ms "${PCA9685_ORDINARY_SHARP_HOLD_MS}"
    --pca9685-sharp-curve-threshold "${PCA9685_SHARP_CURVE_THRESHOLD}"
    --pca9685-sharp-curve-hold-ms "${PCA9685_SHARP_CURVE_HOLD_MS}"
    --pca9685-sharp-curve-outer-scale "${PCA9685_SHARP_CURVE_OUTER_SCALE}"
    --pca9685-sharp-curve-inner-reverse-scale "${PCA9685_SHARP_CURVE_INNER_REVERSE_SCALE}"
    --pca9685-sharp-curve-entry-min-row-ratio "${PCA9685_SHARP_CURVE_ENTRY_MIN_ROW_RATIO}"
    --pca9685-sharp-curve-visible-commit-ms "${PCA9685_SHARP_CURVE_VISIBLE_COMMIT_MS}"
    --pca9685-sharp-curve-finish-inner-reverse-scale "${PCA9685_SHARP_CURVE_FINISH_INNER_REVERSE_SCALE}"
    --pca9685-sharp-curve-exit-settle-ms "${PCA9685_SHARP_CURVE_EXIT_SETTLE_MS}"
    --pca9685-sharp-curve-exit-throttle-scale "${PCA9685_SHARP_CURVE_EXIT_THROTTLE_SCALE}"
    --pca9685-sharp-curve-exit-max-correction-us "${PCA9685_SHARP_CURVE_EXIT_MAX_CORRECTION_US}"
    --pca9685-sharp-curve-recovery-ms "${PCA9685_SHARP_CURVE_RECOVERY_MS}"
    --pca9685-sharp-curve-recovery-max-correction-us "${PCA9685_SHARP_CURVE_RECOVERY_MAX_CORRECTION_US}"
    --pca9685-green-turn-us "${PCA9685_GREEN_TURN_US}"
    --pca9685-green-half-turn-us "${PCA9685_GREEN_HALF_TURN_US}"
    --pca9685-green-half-turn-ms "${PCA9685_GREEN_HALF_TURN_MS}"
    --pca9685-green-half-turn-first-ms "${PCA9685_GREEN_HALF_TURN_FIRST_MS}"
    --pca9685-green-half-turn-second-ms "${PCA9685_GREEN_HALF_TURN_SECOND_MS}"
    --pca9685-green-half-turn-reverse-ms "${PCA9685_GREEN_HALF_TURN_REVERSE_MS}"
)

if [[ -n "${FZ_ROBOT_SERIAL_PORT:-}" ]]; then
    ARGS+=(--robot-serial-port "${FZ_ROBOT_SERIAL_PORT}")
fi

if [[ -n "${PCA9685_BASE_THROTTLE_US}" ]]; then
    ARGS+=(--pca9685-base-throttle-us "${PCA9685_BASE_THROTTLE_US}")
fi

if fz_bool_enabled "${FZ_ROBOT_DRY_RUN:-0}"; then
    ARGS+=(--robot-dry-run)
fi

if fz_bool_enabled "${PCA9685_START_DISARMED}"; then
    ARGS+=(--pca9685-start-disarmed)
else
    ARGS+=(--no-pca9685-start-disarmed)
fi

if fz_bool_enabled "${PCA9685_SIMPLE_LINE_FOLLOW}"; then
    ARGS+=(--pca9685-simple-line-follow)
fi

if fz_bool_enabled "${PCA9685_BASIC_LINE_FOLLOW}"; then
    ARGS+=(--pca9685-basic-line-follow)
fi

if fz_bool_enabled "${PCA9685_GAP_CROSSING_ENABLED}"; then
    ARGS+=(--pca9685-gap-crossing-enabled)
else
    ARGS+=(--no-pca9685-gap-crossing-enabled)
fi

if fz_bool_enabled "${PCA9685_LINE_STEERING_INVERTED}"; then
    ARGS+=(--pca9685-line-steering-inverted)
else
    ARGS+=(--no-pca9685-line-steering-inverted)
fi

if fz_bool_enabled "${PCA9685_SHARP_CORNER_MANEUVER_ENABLED}"; then
    ARGS+=(--pca9685-sharp-corner-maneuver-enabled)
else
    ARGS+=(--no-pca9685-sharp-corner-maneuver-enabled)
fi

if fz_bool_enabled "${PCA9685_CORNER_SEQUENCE_ENABLED}"; then
    ARGS+=(--pca9685-corner-sequence-enabled)
else
    ARGS+=(--no-pca9685-corner-sequence-enabled)
fi

if fz_bool_enabled "${PCA9685_GREEN_MANEUVERS_ENABLED}"; then
    ARGS+=(--pca9685-green-maneuvers-enabled)
else
    ARGS+=(--no-pca9685-green-maneuvers-enabled)
fi

if fz_bool_enabled "${FZ_LINE_ONLY:-0}"; then
    ARGS+=(--line-only)
fi

if fz_bool_enabled "${FZ_ENABLE_LEDS:-0}"; then
    ARGS+=(--enable-leds --led1-gpio "${LED1_GPIO}" --led2-gpio "${LED2_GPIO}")
fi

if fz_bool_enabled "${ENABLE_MASTER_SWITCH}"; then
    ARGS+=(
        --enable-master-switch
        --master-switch-gpio "${MASTER_SWITCH_GPIO}"
        --master-switch-debounce-ms "${MASTER_SWITCH_DEBOUNCE_MS}"
    )
else
    ARGS+=(--no-enable-master-switch)
fi

if [[ -n "${PCA9685_LEFT_CHANNELS}" ]]; then
    ARGS+=(--pca9685-left-channels "${PCA9685_LEFT_CHANNELS}")
fi

if [[ -n "${PCA9685_RIGHT_CHANNELS}" ]]; then
    ARGS+=(--pca9685-right-channels "${PCA9685_RIGHT_CHANNELS}")
fi

if fz_bool_enabled "${FZ_PCA9685_LEFT_INVERTED:-0}"; then
    ARGS+=(--pca9685-left-inverted)
else
    ARGS+=(--no-pca9685-left-inverted)
fi

if fz_bool_enabled "${FZ_PCA9685_RIGHT_INVERTED:-1}"; then
    ARGS+=(--pca9685-right-inverted)
else
    ARGS+=(--no-pca9685-right-inverted)
fi

if [[ -n "${PROFILE_NAME}" ]]; then
    ARGS+=(--profile "${PROFILE_NAME}")
fi

if [[ -n "${RECORDINGS_ROOT}" ]]; then
    ARGS+=(--recordings-root "${RECORDINGS_ROOT}")
fi

export PYTHONUNBUFFERED=1
cd "${FZ_REPO_ROOT}"
exec "${PYTHON_BIN}" "${ARGS[@]}" "${EXTRA_ARGS[@]}"
